# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request]

jobs:
  build-fabric-1-21-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./Fabric-1.21.1
        run: chmod +x ./gradlew

      - name: build Fabric 1.21.1
        working-directory: ./Fabric-1.21.1
        run: ./gradlew build

      - name: upload artifacts Fabric 1.21.1
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-1.21.1-artifacts
          path: Fabric-1.21.1/build/libs/

  build-fabric-1-21-11:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./Fabric-1.21.11
        run: chmod +x ./gradlew

      - name: build Fabric 1.21.11
        working-directory: ./Fabric-1.21.11
        run: ./gradlew build

      - name: upload artifacts Fabric 1.21.11
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-1.21.11-artifacts
          path: Fabric-1.21.11/build/libs/

  build-fabric-1-20-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./Fabric-1.20.1
        run: chmod +x ./gradlew

      - name: build Fabric 1.20.1
        working-directory: ./Fabric-1.20.1
        run: ./gradlew build

      - name: upload artifacts Fabric 1.20.1
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-1.20.1-artifacts
          path: Fabric-1.20.1/build/libs/

  build-fabric-26-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./Fabric-26.1
        run: chmod +x ./gradlew

      - name: build Fabric 26.1
        working-directory: ./Fabric-26.1
        run: ./gradlew build

      - name: upload artifacts Fabric 26.1
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-26.1-artifact
          path: Fabric-26.1/build/libs/

  build-fabric-26-2:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./Fabric-26.2
        run: chmod +x ./gradlew

      - name: build Fabric 26.2
        working-directory: ./Fabric-26.2
        run: ./gradlew build

      - name: upload artifacts Fabric 26.2
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-26.2-artifact
          path: Fabric-26.2/build/libs/

  build-neoforge-1-21-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./NeoForge-1.21.1
        run: chmod +x ./gradlew

      - name: build NeoForge 1.21.1
        working-directory: ./NeoForge-1.21.1
        run: ./gradlew build

      - name: upload artifacts NeoForge 1.21.1
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-1.21.1-artifacts
          path: NeoForge-1.21.1/build/libs/

  build-forge-1-20-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./Forge-1.20.1
        run: chmod +x ./gradlew

      - name: build Forge 1.20.1
        working-directory: ./Forge-1.20.1
        run: ./gradlew build

      - name: upload artifacts Forge 1.20.1
        uses: actions/upload-artifact@v4
        with:
          name: Forge-1.20.1-artifacts
          path: Forge-1.20.1/build/libs/

  build-neoforge-26-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "microsoft"
      - name: make gradle wrapper executable
        working-directory: ./NeoForge-26.1
        run: chmod +x ./gradlew

      - name: build NeoForge 26.1
        working-directory: ./NeoForge-26.1
        run: ./gradlew build

      - name: upload artifacts NeoForge 26.1
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-26.1-artifacts
          path: NeoForge-26.1/build/libs/
